Celery setup and stats schema
the-dive/dive-server pull request #43
Opened 2023-02-02 05:51 UTC by k9845

Resolves xxx (eg: #1 dive/dive-server#1) \
Depends on xxx (eg: #1 dive/dive-server#1)

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2023-02-02 08:28 UTC, bewakes requested changes

2023-02-06 09:33 UTC, k9845 commented on apps/core/schema.py
> +            .values_list("data_rows")[0]
Done

2023-02-06 09:33 UTC, k9845 commented on apps/core/schema.py
> +            Snapshot.objects.filter(table=root.id)
Done

2023-02-06 09:33 UTC, k9845 commented on apps/core/schema.py
> +            Snapshot.objects.filter(table=root.id)
Done

2023-02-06 10:56 UTC, bewakes approved these changes

2023-02-06 10:56 UTC, merged